/**************************************************************************
 * Copyright (c) 2006-2018 ZheJiang Electronic Port, Inc.
 * All rights reserved.
 *
 * 项目名称：西柳场站管理系统
 * 版权说明：本软件属浙江电子口岸有限公司所有，在未获得浙江电子口岸有限公司正式授权
 *           情况下，任何企业和个人，不能获取、阅读、安装、传播本软件涉及的任何受知
 *           识产权保护的内容。
 ***************************************************************************/
package cn.gov.zjport.xlcz.domain.vo;

import java.io.Serializable;
import java.util.Date;

public class Dic implements Serializable {
    /** 主键 */
    private Integer id;

    /** 字典代码 */
    private String dicCode;

    /** 字典名称 */
    private String dicName;

    /** 字典值 */
    private String dicValue;

    /** 字典序号 */
    private Integer dicOrder;

    /** 上级字典(0:顶级) */
    private Integer pid;

    /** 备注 */
    private String remark;

    /** 删除标志（0-未删除，1-已删除） */
    private String deletedFlag;

    /** 创建人 */
    private Integer createId;

    /** 创建时间 */
    private Date createTime;

    /** 修改人 */
    private Integer modifyId;

    /** 修改时间 */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dic
     */
    private static final long serialVersionUID = 1L;

    /**
     * @return the value of id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param id the value for id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * @return the value of dic_code
     */
    public String getDicCode() {
        return dicCode;
    }

    /**
     * @param dicCode the value for dic_code
     */
    public void setDicCode(String dicCode) {
        this.dicCode = dicCode == null ? null : dicCode.trim();
    }

    /**
     * @return the value of dic_name
     */
    public String getDicName() {
        return dicName;
    }

    /**
     * @param dicName the value for dic_name
     */
    public void setDicName(String dicName) {
        this.dicName = dicName == null ? null : dicName.trim();
    }

    /**
     * @return the value of dic_value
     */
    public String getDicValue() {
        return dicValue;
    }

    /**
     * @param dicValue the value for dic_value
     */
    public void setDicValue(String dicValue) {
        this.dicValue = dicValue == null ? null : dicValue.trim();
    }

    /**
     * @return the value of dic_order
     */
    public Integer getDicOrder() {
        return dicOrder;
    }

    /**
     * @param dicOrder the value for dic_order
     */
    public void setDicOrder(Integer dicOrder) {
        this.dicOrder = dicOrder;
    }

    /**
     * @return the value of pid
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * @param pid the value for pid
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * @return the value of remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the value for remark
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * @return the value of deleted_flag
     */
    public String getDeletedFlag() {
        return deletedFlag;
    }

    /**
     * @param deletedFlag the value for deleted_flag
     */
    public void setDeletedFlag(String deletedFlag) {
        this.deletedFlag = deletedFlag == null ? null : deletedFlag.trim();
    }

    /**
     * @return the value of create_id
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * @param createId the value for create_id
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * @return the value of create_time
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime the value for create_time
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * @return the value of modify_id
     */
    public Integer getModifyId() {
        return modifyId;
    }

    /**
     * @param modifyId the value for modify_id
     */
    public void setModifyId(Integer modifyId) {
        this.modifyId = modifyId;
    }

    /**
     * @return the value of modify_time
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * @param modifyTime the value for modify_time
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     *
     * @return String
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dicCode=").append(dicCode);
        sb.append(", dicName=").append(dicName);
        sb.append(", dicValue=").append(dicValue);
        sb.append(", dicOrder=").append(dicOrder);
        sb.append(", pid=").append(pid);
        sb.append(", remark=").append(remark);
        sb.append(", deletedFlag=").append(deletedFlag);
        sb.append(", createId=").append(createId);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyId=").append(modifyId);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}